### PR TITLE
Changed the sequence as gatewayconfig could prevent upnpc execution

### PR DESCRIPTION
**Pull request by MuratUrsavas**
A follow-up for PR #165.

Just changed the sequence of the execution so that upnpc runs before gatewayconfig.

- [x] Tests added
- [x] Cleaned up commit history (rebase!)
- [x] Documentation added
- [x] Thought about variable and method names

### CODE REVIEW

**Review by vpetersson — CHANGES_REQUESTED** [review]
We don't care about DBUS for upnp. Just fire it off earlier, like on line 22.

**Review by vpetersson — COMMENTED** [review]
LGTM but can you double check what exit codes to be expected from `upnpc`?

**Comment by MuratUrsavas** [comment]
> LGTM but can you double check what exit codes to be expected from `upnpc`?

What should we do with these codes?

**Comment by vpetersson** [comment]
> > LGTM but can you double check what exit codes to be expected from `upnpc`?
> 
> What should we do with these codes?

That's just basic (ba)sh. The exit code will determine the behavior of the next commands. For instance, if you run with the shebang `#/bin/bash -e` (or in any [strict mode](http://redsymbol.net/articles/unofficial-bash-strict-mode/)), the exit code  will impact the runtime. If it gets a non-zero response, the script will stop.

**Comment by MuratUrsavas** [comment]
Good point. Let me see if I can find something.

**Comment by MuratUrsavas** [comment]
From what I see we're not running the script in Strict Mode. (Haven't see the -e key). Let's say we're running it in Strict Mode, how could we prevent the script from quitting? A non zero exit would exit anyway.

**Comment by vpetersson** [comment]
> From what I see we're not running the script in Strict Mode. (Haven't see the -e key). Let's say we're running it in Strict Mode, how could we prevent the script from quitting? A non zero exit would exit anyway.

Correct. We're not running in strict mode at this point. However that is something I do want to add in the future as it makes the script 'fail fast' and we'll quickly pick up on crashes/errors rather than just silently suppress them. 

We will likely add the following shebang later:

    #!/bin/bash
    set -euo pipefail
    IFS=$'\n\t'

For now, we just need to understand what the possible error codes are. If it always returns `0`, then fine, we don't need to do anything. If however it returns a non-zero for some use cases, we need to later on add logic for that.

**Comment by MuratUrsavas** [comment]
Gotcha! Working on that.

**Review by shawaj — APPROVED** [review]

**Comment by MuratUrsavas** [comment]
OK, checked the source code of miniupnpc and seen that runtime error return is not possible with current logic. We have three possible non-zero returns

```
-1 on Windows WSAStartup() failed.
1, 2: Parameter assertion error.
```

-1 is only possible on Windows so it's ruled out. 1 and 2 is returned only if there is some kind of parameter assertion error. If we're confident with our command (and we are) this is not possible. But enabling Strict Mode could help in the future if one of us make a typo in the command. It would fail immediately and the developer could catch the problem easily on the first run.

I think it's time to approve this PR.

**Pull request merged**
