### PR TITLE
Create setenv.sh

### PR DESCRIPTION
**Pull request by shawaj**
**Issue**

- Link:
- Summary:

**How**

**Screenshots**

**References**

**Checklist**

- [ ] Tests added
- [ ] Cleaned up commit history (rebase!)
- [ ] Documentation added
- [ ] Thought about variable and method names

### CODE REVIEW

**Comment by KevinWassermann94** [comment]
@shawaj We need to source it in the start-gateway-config.sh and add it to the dockerfile too

**Comment by KevinWassermann94** [comment]
@shawaj This one for the dockerfile:
`COPY setenv.sh /opt/nebra/setenv.sh`

**Comment by shawaj** [comment]
> @shawaj This one for the dockerfile: `COPY setenv.sh /opt/nebra/setenv.sh`

It's already in there

**Comment by shawaj** [comment]
https://github.com/NebraLtd/hm-config/blob/13f1eb5b1887df09db3111dc9c258c6f56280c69/Dockerfile#L68

**Review by KevinWassermann94 — APPROVED** [review]

**Review by kashifpk — APPROVED** [review]

**Review by pritamghanghas — APPROVED** [review]

**Pull request merged**
