### PR TITLE
feat: add support for pisces p100

### PR DESCRIPTION
**Pull request by shawaj**
**Issue**

- Link: https://github.com/NebraLtd/hm-pyhelper/issues/130
- Summary: add pisces p100 support

**How**

bump hm-pyhelper to add pisces p100 support

**Screenshots**

**References**

https://github.com/NebraLtd/hm-pyhelper/issues/130
https://github.com/NebraLtd/hm-pyhelper/issues/131
https://github.com/NebraLtd/hm-pyhelper/issues/133
https://github.com/NebraLtd/helium-miner-software/pull/381
https://github.com/NebraLtd/hm-pktfwd/pull/87
https://github.com/NebraLtd/hm-block-tracker/pull/80
https://github.com/NebraLtd/hm-miner/pull/75

**Checklist**

- [x] Tests added
- [x] Cleaned up commit history (rebase!)
- [x] Documentation added
- [x] Thought about variable and method names

### CODE REVIEW

**Comment by shawaj** [comment]
Security scan failing due to following:

```
Test results:
>> Issue: [B105:hardcoded_password_string] Possible hardcoded password: ''
   Severity: Low   Confidence: Medium
   CWE: CWE-259 (https://cwe.mitre.org/data/definitions/259.html)
   Location: ./gatewayconfig/bluetooth/characteristics/wifi_connect_characteristic.py:28:29
   More Info: https://bandit.readthedocs.io/en/1.7.3/plugins/b105_hardcoded_password_string.html
27	        self.wifi_service = ""
28	        self.wifi_password = ""
29	

--------------------------------------------------
>> Issue: [B105:hardcoded_password_string] Possible hardcoded password: ''
   Severity: Low   Confidence: Medium
   CWE: CWE-259 (https://cwe.mitre.org/data/definitions/259.html)
   Location: ./gatewayconfig/bluetooth/characteristics/wifi_connect_characteristic.py:85:33
   More Info: https://bandit.readthedocs.io/en/1.7.3/plugins/b105_hardcoded_password_string.html
84	            self.wifi_service = ""
85	            self.wifi_password = ""
86	
```

**Comment by marvinmarnold** [comment]
> @marvinmarnold @vpetersson do you think we can ignore these? or is there a way we can fix/remove these?

We might be able to make the default `None` but I vaguely remember there being a reason that wouldn't work. This seems fine for now as it's not actually a default password.

**Comment by shawaj** [comment]
@marvinmarnold yeah agreed on that :-)

**Review by marvinmarnold — APPROVED** [review]
Forgot to approve

**Pull request merged**
