### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by shawaj**
**Issue**

- Link:
- Summary:

**How**

**Screenshots**

**References**

**Checklist**

- [ ] Tests added
- [ ] Cleaned up commit history (rebase!)
- [ ] Documentation added
- [ ] Thought about variable and method names

### CODE REVIEW

**Comment by shawaj** [comment]
@KevinWassermann94 this build should fix the issue in #227 but it is a very hacky way of achieving this...before putting live on actual production units we should have radxa fix the actual debian package for libmraa on bullseye.

do you agree? 

if so, we can roll back the config container in helium-miner-software and test with the older config container. then we can finish testing and deploy the diagnostics changes to production when we are ready and have documentation etc

**Comment by pritamghanghas** [comment]
just for my awareness, why do we need bullseye? Is there a LTS issue in current release?

**Comment by KevinWassermann94** [comment]
@shawaj Yeah, let's wait for Radxa to fix it to make sure we don't run into any undetected issues

**Comment by shawaj** [comment]
> just for my awareness, why do we need bullseye? Is there a LTS issue in current release?

Main reason was just because buster is EOL as of last year. I know it's on LTS but IMO it's better to use current stable wherever possible (although I realise that this is probably a contentious issue 😂). Especially given that Bookworm is on its way.

But also to unify the base images between all containers so the overall image size is reduced

**Comment by shawaj** [comment]
> @shawaj Yeah, let's wait for Radxa to fix it to make sure we don't run into any undetected issues

👌

**Pull request closed without merging**
