### PR TITLE
Fixes parsing from latest GA release

### PR DESCRIPTION
**Pull request by vpetersson**
**Why**
Fixes parsing issue from latest GA release

**How**
Manually tested on TestNet miner.

**References**
https://github.com/NebraLtd/hm-config/issues/63

### CODE REVIEW

**Comment by shawaj** [comment]
@vpetersson probably better to put this onto this branch instead of master https://github.com/NebraLtd/hm-config/tree/fix_handler_typeerror

Master has **lots** of untested changes

**Comment by vpetersson** [comment]
> @vpetersson probably better to put this onto this branch instead of master https://github.com/NebraLtd/hm-config/tree/fix_handler_typeerror
> 
> Master has **lots** of untested changes

Oh good shout. Let me take a closer look. I thought we were running on master.

**Comment by shawaj** [comment]
@vpetersson we are running on a really old master

**Comment by vpetersson** [comment]
> @vpetersson we are running on a really old master

Actually, I `diff`'d master against what we're running on the miners, and they're just cosmetic changes really.

**Comment by shawaj** [comment]
I think if you just revert this change - https://github.com/NebraLtd/hm-config/commit/bfb80d4334b06bd03c64df3120538d4981bd73cf on that branch then it's essentially the current one.

Or roll back to 61b77e8011413d19aa36c9bb681df0d48c054fbd and then add your changes to that on a new branch

**Comment by shawaj** [comment]
Ah ok, well if it works it works!

**Review by robputt — APPROVED** [review]

**Comment by shawaj** [comment]
Need to bump bluez to rpt2 as in #60

**Comment by shawaj** [comment]
Oh and the variant definitions file too...

**Comment by vpetersson** [comment]
One thing at the time @shawaj. Let's fix this particular thing first.

**Comment by shawaj** [comment]
> One thing at the time @shawaj. Let's fix this particular thing first.

@vpetersson the docker images won't build unless you fix those...

**Comment by vpetersson** [comment]
Ah ok. Just looked at the logs.

**Comment by vpetersson** [comment]
Actually. I was wrong. There are a lot of changes in master.

**Comment by vpetersson** [comment]
Ok looking closer, these are just lint fixes really. Not too worried about deploying them. Let's get this to pass and merge it in. Then deploy it to testnet.

**Pull request merged**
