### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by robputt**

### CODE REVIEW

**Comment by robputt** [comment]
Ready for review @vpetersson a few notes...

- Please test this before merge, it's likely this could break something as the code base had to be modified somewhat to accommodate tests. Not ideal, but theoretically should be compatible.
- Unit test coverage only reaches 58%, the config_program.py is written in a way which is largely untestable, it needs a large refactor although before we embark on that endeavour we should try and merge in the tests we have created without needing such major modifications.

**Comment by vpetersson** [comment]
I'm afk for a few hours.

**Comment by vpetersson** [comment]
@robputt Looks like i dropped the ball on this and got @ilyastrodubtsev to duplicate some of this. Would you mind pulling in master once https://github.com/NebraLtd/hm-config/pull/50 has been landed?

**Comment by shawaj** [comment]
Closed by #61 ?

**Pull request closed without merging**
